### ISSUE TITLE
when ever I try to put it into my game I get a error

### ISSUE THREAD

**Issue by Gothbr4dn** [MAJigsaw77/hxgamejolt-api#4]
Error: Could not find haxelib "gamejolt-integration", does it need to be installed?

after I changed it to the githubs name
Error: Could not find haxelib "Haxe-GameJolt-Integration", does it need to be installed?

also this isn't FNF incase you needed to know

**Comment by MAJigsaw77** [comment]
In your project.xml add:
```xml
<haxelib name="gamejolt-integration" />
```

**Comment by MAJigsaw77** [comment]
After you install like how I said in the read me.

**Comment by MAJigsaw77** [comment]
Better look in the readme again now.
