### ISSUE TITLE
thread related crash

### ISSUE THREAD

**Issue by BrosterMedia** [MAJigsaw77/hxgamejolt-api#9]
I'm currently setting up a scoreboard system.
often at random times i get a thread error thrown at me

`Called from sys.thread._Thread.HaxeThread::create C:\HaxeToolkit\haxe\std/cpp/_std/sys/thread/Thread.hx line 130
Critical Error: Uncatchable Throw: Null Object Reference`

my current setup for this is nothing more than
```
GameJolt.fetchScore(10, tableID, null, null, null, null, null,  {
            onSucceed: function(response:Dynamic):Void
                {
                    for (i in 0...response.scores.length)
                    {
                        var userName:FlxText = new FlxText(150, 100 + 70 * i, 400, '#${i+1} ${response.scores[i].user}', 16);
                        add(userName);
                    }
                },
                onFail: function(message:String):Void
                {
                    trace(message);
                }
        });
```

**Comment by MAJigsaw77** [comment]
Try not creating the text within the thread, instead, change only the text within it.

**Comment by BrosterMedia** [comment]
ah, yeah that seemed to work, thanks!
